@InitializeData.sql

SET ECHO ON

SET SERVEROUTPUT ON SIZE UNLIMITED

SPOOL output-Ex5-Scenario2.txt

VARIABLE input VARCHAR2(30)

-- Create the AuditLog table
CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    LogDate DATE,
    Action VARCHAR2(50)
);

-- Trigger to insert a record into the AuditLog table whenever a transaction is inserted
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, LogDate, Action)
    VALUES (:NEW.TransactionID, SYSDATE, 'Transaction Inserted');
END;
/

-- Test the trigger by inserting a transaction
INSERT INTO TRANSACTIONS (TransactionID, ACCOUNTID, TRANSACTIONDATE, AMOUNT, TRANSACTIONTYPE)
VALUES (3001, 1, SYSDATE, 500, 'Deposit');

-- Verify the audit log entry
SELECT * FROM AuditLog;

SPOOL OFF

DROP TABLE AuditLog;

@DropData.sql
